### ISSUE TITLE
无法在 Idea K2 模式下启动

### ISSUE THREAD

**Issue by xiaozhangup** [TabooLib/taboolib-intellij#13]
如果Idea打开了K2模式，这个插件就没法加载了。

**Comment by EmptyIrony** [comment]
[commit](https://github.com/TabooLib/taboolib-development/commit/85105d3306583b8787f19fe6b079c874c03759c7) 
修了
1.3版本送审了

**Comment by xiaozhangup** [comment]
感谢
---- 回复的原邮件 ----
| 发件人 | Jerry ***@***.***> |
| 发送日期 | 2024年11月4日 16:07 |
| 收件人 | ***@***.***> |
| 抄送人 | Daniel ***@***.***>,
***@***.***> |
| 主题 | Re: [TabooLib/taboolib-development] 无法在 Idea K2 模式下启动 (Issue #13) |

https://github.com/TabooLib/taboolib-development/commit/85105d3306583b8787f19fe6b079c874c03759c7
修了
1.3版本送审了

**Comment by EmptyIrony** [comment]
1.3 版本已修复 并已过审

**Comment by xiaozhangup** [comment]
感谢


---- 回复的原邮件 ----
| 发件人 | Jerry ***@***.***> |
| 发送日期 | 2024年11月7日 17:01 |
| 收件人 | ***@***.***> |
| 抄送人 | Daniel ***@***.***>,
***@***.***> |
| 主题 | Re: [TabooLib/taboolib-development] 无法在 Idea K2 模式下启动 (Issue #13) |

1.3 版本已修复 并已过审
