### ISSUE TITLE
Download module list failed

### ISSUE THREAD

**Issue by ShawnMerryCode** [TabooLib/taboolib-intellij#14]
如图所示，在创建项目页面填好信息之后无法继续下一步，弹出提示框，标题`Download module list failed`，内容`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certifitcation path to requested target`

![图片](https://github.com/user-attachments/assets/472eda27-546b-46d0-b166-17568307ee74)
***
补充：经排查，是FastGithub会修改证书

**Comment by ShawnMerryCode** [comment]
FastGithub修改了证书，导致SSL识别出问题

**Comment by ShawnMerryCode** [comment]
新的问题：请求的名称有效，但找不到请求的类型的数据

![image](https://github.com/user-attachments/assets/6bb2d718-d04d-47fe-b3cc-d6c9e5e180b9)

**Comment by ShawnMerryCode** [comment]
问题已经解决。

**Comment by zhangfu-liu** [comment]
> 问题已经解决。

这个如何解决的呢

**Comment by ShawnMerryCode** [comment]
> > 问题已经解决。
> 
> 这个如何解决的呢

第一个问题（SSL）是因为我装的软件会修改Github的SSL证书导致无法验证，第二个（找不到数据）则是因为国内raw.githubusercontent.com有时候有问题，需要更改系统hosts文件
